[tool.poetry]
name = "lfsbug"
version = "0.1.0"
description = ""
authors = [
]

[tool.poetry.dependencies]
importlib-resources = "^5.8"
numpy = "^1.19.5"
python = "^3.9"
zstandard = "^0.18.0"


[tool.poetry.dev-dependencies]
black = "^23.10.0"

